# solace/manifests.yaml (Versi Final dengan perbaikan /dev/shm)

# Secret untuk admin user (tetap sama)
apiVersion: v1
kind: Secret
metadata:
  name: solace-secret
  namespace: solace
stringData:
  username_admin_password: "PasswordSolace123"
---
# StatefulSet untuk menjalankan broker Solace (dengan perbaikan)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solace-pubsub
  namespace: solace
spec:
  serviceName: "solace-service"
  replicas: 1
  selector:
    matchLabels:
      app: solace
  template:
    metadata:
      labels:
        app: solace
    spec:
      initContainers:
      - name: init-solace
        image: busybox
        command: ['sh', '-c', 'ulimit -n 2448 && ulimit -u 2048']
        securityContext:
          privileged: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      # --- PENAMBAHAN KUNCI: Mendefinisikan volume untuk /dev/shm ---
      volumes:
        # Mendefinisikan volume memory-backed bernama 'dshm'
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi # Memberikan 2Gi, lebih dari cukup dari 1Gi yang diminta
      - name: solace-storage # Ini adalah volume persistent yang sudah ada
        persistentVolumeClaim:
          claimName: solace-storage # Pastikan ini cocok dengan nama PVC yang dibuat oleh volumeClaimTemplates
      containers:
      - name: solace
        image: solace/solace-pubsub-standard:latest
        env:
          - name: username_admin_password
            valueFrom:
              secretKeyRef:
                name: solace-secret
                key: username_admin_password
        resources:
          requests:
            memory: "3Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "1500m"
        ports:
          - containerPort: 8080
            name: web
          - containerPort: 55555
            name: smf
          - containerPort: 5672
            name: amqp
        volumeMounts:
        # --- PENAMBAHAN KUNCI: Memasang volume 'dshm' ke /dev/shm ---
        - name: dshm
          mountPath: /dev/shm
        - name: solace-storage # Mount untuk data persistent
          mountPath: /usr/sw/var
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: solace-storage # PVC untuk data persistent
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
# Service (tetap sama)
apiVersion: v1
kind: Service
metadata:
  name: solace-service
  namespace: solace
spec:
  type: NodePort
  selector:
    app: solace
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31444
    - name: smf
      protocol: TCP
      port: 55555
      targetPort: 55555
      nodePort: 31443
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 31445