# ===================================================================
# ANNOTATED SOLACE DEPLOYMENT FOR KUBERNETES
#
# This manifest is adapted from the standard 'docker run' command
# to ensure all necessary configurations are included.
# ===================================================================

# =====================================
# Namespace: solace
# A dedicated namespace to logically isolate the Solace resources.
# =====================================
apiVersion: v1
kind: Namespace
metadata:
  name: solace
---
# =====================================
# Secret: solace-secret
# Stores sensitive data, like the admin password, separately from
# the Pod definition for better security.
# =====================================
apiVersion: v1
kind: Secret
metadata:
  name: solace-secret
  namespace: solace
stringData:
  # The password for the 'admin' user of the Solace broker.
  username_admin_password: "admin" # Menggunakan password dari contoh docker run
---
# =====================================
# StatefulSet: solace-pubsub
# Manages the Solace Pod. A StatefulSet is used because it provides
# stable, unique network identifiers and stable, persistent storage.
# =====================================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solace-pubsub
  namespace: solace
spec:
  serviceName: "solace-service"
  replicas: 1
  selector:
    matchLabels:
      app: solace
  template:
    metadata:
      labels:
        app: solace
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: solace
          image: solace/solace-pubsub-standard:10.25.0
          env:
            # --- PERBAIKAN: Menambahkan variabel lingkungan dari docker run ---
            - name: username_admin_globalaccesslevel
              value: "admin"
            - name: username_admin_password
              valueFrom:
                secretKeyRef:
                  name: solace-secret
                  key: username_admin_password
            - name: SOLACE_LOG_TO_STDOUT
              value: "yes"
            - name: SOLACE_CHECK_RSYSLOG
              value: "no"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1500m"
            limits:
              memory: "3Gi"
              cpu: "2500m"
          ports:
            # --- PERBAIKAN: Menambahkan semua port dari docker run ---
            - containerPort: 8080 # Web UI
              name: web
            - containerPort: 55555 # SMF
              name: smf
            - containerPort: 8008  # SEMP over TLS
              name: semp-tls
            - containerPort: 1883  # MQTT
              name: mqtt
            - containerPort: 8000  # MQTT over WS
              name: mqtt-ws
            - containerPort: 5672  # AMQP
              name: amqp
            - containerPort: 9000  # MQTT Secure
              name: mqtt-secure
            - containerPort: 2222  # CLI Secure
              name: cli-secure
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: solace-storage
              mountPath: /usr/sw/var
          securityContext:
            privileged: true
      volumes:
        # --- PERBAIKAN: Menyesuaikan ukuran SHM dengan docker run (--shm-size=2g) ---
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: solace-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
---
# =====================================
# Service: solace-service (LoadBalancer)
# Exposes the Solace Pod to the internet via a cloud Load Balancer.
# =====================================
apiVersion: v1
kind: Service
metadata:
  name: solace-service
  namespace: solace
spec:
  # --- PERBAIKAN: Mengubah tipe Service menjadi LoadBalancer ---
  # Ini akan secara otomatis membuat Load Balancer di provider cloud Anda.
  type: LoadBalancer
  selector:
    app: solace
  ports:
    # --- PERBAIKAN: Menambahkan semua port dari docker run ---
    # NodePort tidak perlu didefinisikan secara manual saat menggunakan LoadBalancer.
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: smf
      protocol: TCP
      port: 55555
      targetPort: 55555
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: semp-tls
      protocol: TCP
      port: 8008
      targetPort: 8008
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mqtt-ws
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: mqtt-secure
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: cli-secure
      protocol: TCP
      port: 2222
      targetPort: 2222
