# =====================================
# Namespace: solace
# =====================================
apiVersion: v1
kind: Namespace
metadata:
  name: solace
---
# =====================================
# Secret: solace-secret
# =====================================
apiVersion: v1
kind: Secret
metadata:
  name: solace-secret
  namespace: solace
stringData:
  username_admin_password: "PasswordSolace123"
---
# =====================================
# StatefulSet: solace-pubsub
# =====================================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: solace-pubsub
  namespace: solace
spec:
  serviceName: "solace-service"
  replicas: 1
  selector:
    matchLabels:
      app: solace
  template:
    metadata:
      labels:
        app: solace
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: solace
          image: solace/solace-pubsub-standard:10.25.0
          env:
            - name: username_admin_password
              valueFrom:
                secretKeyRef:
                  name: solace-secret
                  key: username_admin_password
            - name: SOLACE_LOG_TO_STDOUT
              value: "yes"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1500m"
            limits:
              memory: "3Gi"
              cpu: "2500m"
          ports:
            - containerPort: 8080
              name: web
            - containerPort: 55555
              name: smf
            - containerPort: 5672
              name: amqp
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: solace-storage
              mountPath: /usr/sw/var
          securityContext:
            privileged: true
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: solace-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
# =====================================
# Service: solace-service (NodePort)
# =====================================
apiVersion: v1
kind: Service
metadata:
  name: solace-service
  namespace: solace
spec:
  type: NodePort
  selector:
    app: solace
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31444
    - name: smf
      protocol: TCP
      port: 55555
      targetPort: 55555
      nodePort: 31443
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 31445
