# 1. Namespace untuk mengisolasi SonarQube
apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
---
# 2. Persistent Volume Claims (PVCs) untuk data dan ekstensi SonarQube
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data-pvc
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-extensions-pvc
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# 3. Service untuk SonarQube dengan tipe NodePort
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-svc
  namespace: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - name: sonarqube-ui
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30099
---
# 4. Deployment untuk SonarQube yang terhubung ke PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
      - name: sysctl-init
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: sonarqube
        image: sonarqube:lts-community
        ports:
        - containerPort: 9000
        # --- PERBAIKAN: Menggunakan kredensial secara langsung (Hardcoded) ---
        env:
        - name: SONAR_JDBC_URL
          value: "jdbc:postgresql://postgres-service.postgres-ha:5432/sonar"
        # Username dimasukkan langsung, tidak lagi membaca dari Secret
        - name: SONAR_JDBC_USERNAME
          value: "pguser"
        # Password dimasukkan langsung, tidak lagi membaca dari Secret
        - name: SONAR_JDBC_PASSWORD
          value: "pgpass"
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
        - name: sonarqube-extensions
          mountPath: /opt/sonarqube/extensions
      volumes:
      - name: sonarqube-data
        persistentVolumeClaim:
          claimName: sonarqube-data-pvc
      - name: sonarqube-extensions
        persistentVolumeClaim:
          claimName: sonarqube-extensions-pvc
