# 4. Deployment untuk SonarQube yang terhubung ke PostgreSQL
# FIX: Kredensial database sekarang dimasukkan langsung (hardcoded)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      # PENTING: initContainer untuk mengatur properti kernel
      initContainers:
      - name: sysctl-init
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: sonarqube
        image: sonarqube:lts-community
        ports:
        - containerPort: 9000
        # --- Konfigurasi Koneksi Langsung ke PostgreSQL ---
        env:
        # URL JDBC menunjuk langsung ke IP dan port NodePort PostgreSQL
        - name: SONAR_JDBC_URL
          value: "jdbc:postgresql://43.157.209.107:31001/sonar"
        
        # Username dimasukkan langsung sebagai plain text
        - name: SONAR_JDBC_USERNAME
          value: "pguser"
          
        # Password dimasukkan langsung sebagai plain text (tidak aman)
        - name: SONAR_JDBC_PASSWORD
          value: "pgpass"
          
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
        - name: sonarqube-extensions
          mountPath: /opt/sonarqube/extensions
      volumes:
      - name: sonarqube-data
        persistentVolumeClaim:
          claimName: sonarqube-data-pvc
      - name: sonarqube-extensions
        persistentVolumeClaim:
          claimName: sonarqube-extensions-pvc
