apiVersion: apps/v1
kind: Deployment
metadata:
  # Nama deployment bisa dinamis atau statis
  name: my-springboot-app-deployment
  namespace: default 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-springboot-app
  template:
    metadata:
      labels:
        app: my-springboot-app
    spec:
      containers:
      - name: app
        # Baris ini yang akan diganti oleh Jenkins
        image: airlangga22/my-springboot-app:initial
        ports:
        - containerPort: 8080