apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-app
  namespace: default # atau namespace lain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-springboot-app
  template:
    metadata:
      labels:
        app: my-springboot-app
    spec:
      containers:
      - name: app
        # PENTING: Gunakan 'placeholder' atau image lama sebagai awal.
        # Jenkins akan mengganti baris ini secara otomatis.
        image: your-dockerhub-username/my-springboot-app:initial
        ports:
        - containerPort: 8080
