apiVersion: v1
kind: Service
metadata:
  name: my-springboot-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: my-springboot-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32080 # Gunakan NodePort yang berbeda untuk setiap aplikasi
