apiVersion: v1
kind: Service
metadata:
  name: my-springboot-svc
  namespace: default # atau namespace lain
spec:
  type: NodePort
  selector:
    app: my-springboot-app
  ports:
  - port: 80
    targetPort: 8080