# my-k8s-configs/kai-test-kafka/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kai-test-kafka-config
  namespace: kai-test-kafka
data:
  application.yml: |
    # ==================== PERBAIKAN DI SINI ====================
    # Menambahkan context-path agar aplikasi berjalan di /kai-test-kafka
    server:
      servlet:
        context-path: /kai-test-kafka
      port: 8080
    # =========================================================

    kafka:
      topic:
        presensi-log: presensi-log

    spring:
      application:
        name: kai-test-kafka
      profiles:
        active: development
      kafka:
        bootstrap-servers: 43.157.209.107:30992
        consumer:
          group-id: presensi-log-batch-consumer-group-v3
          auto-offset-reset: earliest
          enable-auto-commit: false
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          fetch-max-wait-ms: 5000
          fetch-min-bytes: 1
          max-poll-records: 500
        listener:
          type: batch
          ack-mode: MANUAL_IMMEDIATE
      
      datasource:
        rolink-master:
          url: jdbc:postgresql://43.157.209.107:31001/mydb?currentSchema=starlink
          username: pguser
          password: pgpass
          driver-class-name: org.postgresql.Driver
          test-while-idle: true
          test-on-borrow: true
          validation-query: SELECT 1
          hikari:
            minimum-idle: 5
            maximum-pool-size: 20
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 30000
        rolink-slave:
          url: jdbc:postgresql://43.157.209.107:31001/mydb?currentSchema=starlink
          username: pguser
          password: pgpass
          driver-class-name: org.postgresql.Driver
          test-while-idle: true
          test-on-borrow: true
          validation-query: SELECT 1
          hikari:
            minimum-idle: 5
            maximum-pool-size: 20
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 30000

      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
          hibernate:
            jdbc:
              batch_size: 50
            order_inserts: true
            order_updates: true
            batch_versioned_data: true
