# my-k8s-configs/kai-test-kafka/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kai-test-kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kai-test-kafka
  template:
    metadata:
      labels:
        app: kai-test-kafka
    spec:
      containers:
      - name: app
        # PENTING: Jenkins akan mengganti baris ini secara otomatis
        image: airlangga2403/kai-test-kafka:initial
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: kai-test-kafka-config
