# my-k8s-configs/kai-test-kafka/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kai-test-kafka-deployment
  # Selalu tentukan namespace agar konsisten
  namespace: kai-test-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kai-test-kafka
  template:
    metadata:
      labels:
        app: kai-test-kafka
    spec:
      # --- LOKASI YANG BENAR UNTUK imagePullSecrets ---
      # 'imagePullSecrets' berada di sini, sejajar dengan 'containers'.
      imagePullSecrets:
      - name: dockerhub-creds
      # -----------------------------------------------
      
      containers:
      - name: app
        # --- LOKASI YANG BENAR UNTUK image ---
        # 'image' adalah properti dari container, bukan dari imagePullSecrets.
        # PENTING: Jenkins akan mengganti baris ini secara otomatis
        image: airlangga2403/kai-test-kafka:initial
        imagePullPolicy: Always # Disarankan untuk selalu pull image terbaru dari registry
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: kai-test-kafka-config
