# my-k8s-configs/kai-test-kafka/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kai-test-kafka-service
spec:
  type: NodePort
  selector:
    app: kai-test-kafka
  ports:
  - port: 8080
    targetPort: 8080
    # Ganti port ini sesuai kebutuhan untuk setiap aplikasi
    nodePort: 30820
