# jenkins/deployment.yaml
# Mendefinisikan deployment untuk Jenkins Controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa # Menggunakan Service Account yang sudah dibuat
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk17 # Menggunakan image LTS (Long-Term Support)
        
        # ==================== PERBAIKAN DI SINI ====================
        # Menambahkan environment variable untuk mengaktifkan WebSocket.
        # Ini akan membuat opsi WebSocket muncul di halaman Security.
        env:
        - name: JAVA_OPTS
          value: "-Dorg.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.USE_WEB_SOCKET=true"
        # =========================================================

        ports:
        - containerPort: 8080
          name: web
        - containerPort: 50000
          name: agent
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc

