# jenkins/service.yaml
# Mengekspos Jenkins UI dan port agent menggunakan NodePort
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32000 # Akses UI Jenkins melalui http://<IP-NODE>:32000
    name: web
  - port: 50000
    targetPort: 50000
    nodePort: 32001 # Port untuk komunikasi dengan build agent
    name: agent