# minio-new/manifests.yaml

# Secret untuk menyimpan kredensial Minio
apiVersion: v1
kind: Secret
metadata:
  # Mengubah nama resource
  name: minio-new-secret
  namespace: minio
stringData:
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "PasswordMinio123"
---
# Persistent Volume Claim untuk menyimpan data Minio
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Mengubah nama resource
  name: minio-new-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
# Deployment untuk menjalankan pod Minio
apiVersion: apps/v1
kind: Deployment
metadata:
  # Mengubah nama resource
  name: minio-new-deployment
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      # Mengubah label selector
      app: minio-new
  template:
    metadata:
      labels:
        # Mengubah label pod
        app: minio-new
    spec:
      containers:
      - name: minio-new
        image: minio/minio:latest
        command:
          - /bin/bash
          - -c
          - |
            minio server /data --console-address ":9001"
        envFrom:
          - secretRef:
              # Mereferensikan secret yang baru
              name: minio-new-secret
        ports:
          - containerPort: 9000
            name: api
          - containerPort: 9001
            name: console
        volumeMounts:
          - name: storage
            mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            # Mereferensikan PVC yang baru
            claimName: minio-new-pvc
---
# Service untuk mengakses API Minio
apiVersion: v1
kind: Service
metadata:
  # Mengubah nama resource
  name: minio-new-api-service
  namespace: minio
spec:
  type: NodePort
  selector:
    # Mengubah label selector
    app: minio-new
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 32000
      name: api
---
# Service untuk mengakses Console Minio
apiVersion: v1
kind: Service
metadata:
  # Mengubah nama resource
  name: minio-new-console-service
  namespace: minio
spec:
  type: NodePort
  selector:
    # Mengubah label selector
    app: minio-new
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 32001
      name: console