apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-internal
  namespace: kafka
  labels:
    app: kafka-test
    unit: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka-test
    unit: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: kafka
  labels:
    app: kafka-test
    unit: kafka
spec:
  type: NodePort
  selector:
    app: kafka-test
    unit: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
      nodePort: 30992
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: "kafka-internal"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-test
      unit: kafka
  template:
    metadata:
      labels:
        app: kafka-test
        unit: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://43.157.209.107:30992
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper:2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
