apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-internal
  namespace: test
  labels:
    app: kafka-test
    unit: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka-test
    unit: kafka
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: test
  labels:
    app: kafka-test
    unit: kafka
spec:
  type: NodePort
  selector:
    app: kafka-test
    unit: kafka
  ports:
    - name: external
      port: 30992
      targetPort: 9094
      nodePort: 30992

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: test
spec:
  serviceName: "kafka-internal"
  replicas: 1
  selector:
    matchLabels:
      app: kafka-test
      unit: kafka
  template:
    metadata:
      labels:
        app: kafka-test
        unit: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
              name: internal
            - containerPort: 9093
              name: controller
            - containerPort: 9094
              name: external
          env:
            # KRaft mode configuration
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-0.kafka-internal.test:9093"
            
            # Fixed: Added controller listener names
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            
            # Listener configuration
            - name: KAFKA_CFG_LISTENERS
              value: "INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-0.kafka-internal.test:9092,EXTERNAL://43.157.209.107:30992"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            
            # Other Kafka settings
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            
            # Resource settings
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx1G -Xms1G"